name: E2E
on: [push]
jobs:
  chrome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
          record: true
          command-prefix: 'percy exec -- npx'

    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      CYPRESS_auth_client_id: ${{ secrets.qa_task_auth_client_id }}
      CYPRESS_auth_password: ${{ secrets.qa_task_auth_password }}
      CYPRESS_auth_url: ${{ secrets.qa_task_auth_url }}
      CYPRESS_auth_username: ${{ secrets.qa_task_auth_username }}
      CYPRESS_credential_type: ${{ secrets.qa_task_credential_type }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.13.0-chrome80-ff74
      options: --user 1001
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          browser: firefox
          headless: false
          record: true
          command-prefix: 'percy exec -- npx'
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      CYPRESS_auth_client_id: ${{ secrets.qa_task_auth_client_id }}
      CYPRESS_auth_password: ${{ secrets.qa_task_auth_password }}
      CYPRESS_auth_url: ${{ secrets.qa_task_auth_url }}
      CYPRESS_auth_username: ${{ secrets.qa_task_auth_username }}
      CYPRESS_credential_type: ${{ secrets.qa_task_credential_type }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}     