name: E2E on Chrome
on: [push]
jobs:
  chrome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
          record: true

  firefox: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          browser: firefox
          headless: true
          record: true

    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      CYPRESS_auth_client_id: ${{ secrets.qa_task_auth_client_id }}
      CYPRESS_auth_password: ${{ secrets.qa_task_auth_password }}
      CYPRESS_auth_url: ${{ secrets.qa_task_auth_url }}
      CYPRESS_auth_username: ${{ secrets.qa_task_auth_username }}
      CYPRESS_credential_type: ${{ secrets.qa_task_credential_type }}